package oopsconcept;

public abstract class Abstractclass {
	
	private String name ;
	private int paymentPerHour;
	


public Abstractclass(String name, int paymenthours) {
		this.name = name ;
		this.paymentPerHour = paymenthours;		
	}

	
	//Abstract methods signature , other class must implement these methods 
	public abstract int calculateSalary();
	public abstract String empname();
	public abstract String empdetails();
	
	public String testname() {
	 return getName();	
	}
	
	//getter and setter methods , can be autogenerated 
	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public int getPaymentPerHour() {
		return paymentPerHour;
	}


	public void setPaymentPerHour(int paymentPerHour) {
		this.paymentPerHour = paymentPerHour;
	}

	
}
